### ISSUE TITLE
Getting error while running gulp dev

### ISSUE THREAD

**Issue by jay3dec** [touchstonejs/touchstonejs-starter#16]
I simply cloned the repository and ran `gulp dev` and it's throwing the following error
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jay/touchstonejs-starter/node_modules/touchstonejs-tasks/node_modules/babel-core/lib/babel/api/node.js:16:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jay/touchstonejs-starter/node_modules/touchstonejs-tasks/node_modules/babelify/index.js:3:15)

```
Doing node server.js works fine though. Any thoughts ?

**Comment by dcousens** [comment]
@jay3dec looks like a break in one of our dependencies.
Namely `babel`, @sebmck? :P

**Comment by sebmck** [comment]
`npm install` probably didn't finish. Run `npm cache clean && rm -rf node_modules` then `npm install` again.

**Comment by jay3dec** [comment]
@sebmck ok I tried as you said.Now i'm able to run the starter app but nothing is seen in the browser. When I check the console, I see the following errors,
```
The key "target-densitydpi" is not supported. localhost/:11
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8000/cordova.js
Download the React DevTools for a better development experience: https://fb.me/react-devtools react.js:4460
2Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components). react.js:21754
Warning: Only functions or strings can be mounted as React components. react.js:21754
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined 
```

**Comment by dcousens** [comment]
@jay3dec did you end up solving this?

**Comment by jay3dec** [comment]
@dcousens it worked thanks

**Comment by mbrookes** [comment]
I'm getting have a different issue, but the title is still relevant, so rather than polute issues with something that may be a config problem on my end, adding it here:
```
> gulp dev
[23:19:19] Using gulpfile ~/Projects/touchstonejs-starter/gulpfile.js
[23:19:19] Starting 'serve'...
[23:19:19] Finished 'serve' after 8.52 ms
[23:19:19] Starting 'html'...
[23:19:19] Starting 'images'...
[23:19:19] Starting 'fonts'...
[23:19:19] Starting 'less'...
[23:19:19] Starting 'scripts-watch'...
[23:19:19] Server started http://localhost:8000
[23:19:19] LiveReload started on port 35729
[23:19:19] Finished 'html' after 113 ms
[23:19:20] Finished 'less' after 1.15 s
[23:19:20] Finished 'fonts' after 1.16 s
[23:19:23] Browserify Error:
           Cannot find module 'react-timers' from '/Users/mbrookes/Projects/touchstonejs-starter/src/js/views'
[23:19:23] Browserify Error:
           Cannot find module 'react-timers' from '/Users/mbrookes/Projects/touchstonejs-starter/src/js/views'
[23:19:23] Browserify Error:
           Cannot find module 'react-timers' from '/Users/mbrookes/Projects/touchstonejs-starter/src/js/views'
[23:19:23] Finished 'images' after 3.86 s
```

In the browser I get a blank fuchsia background, but nothing else.
 
I've tried  `npm cache clean && rm -rf node_modules` then `npm install` again, but no change. 

Any ideas?

**Comment by dcousens** [comment]
@mbrookes is this still the case?   I just pushed `3.4.1` which fixed a broken published build (was missing `lib/` on `npm`).

**Comment by mbrookes** [comment]
Nice one, thanks @dcousens! Closing this... oh, wait! :wink:
